import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

import { useDispatch, useSelector } from 'react-redux'
import { RootState } from '../store'
import { decrement, increment } from '../slices/functionality/counterSlice'
import { Button } from '../components/ui'
import { MainContainer } from '../components/layout'
import { Layout } from '../components/layout/Layout'

import Logotype from "../public/images/usuaal.svg"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const counter = useSelector((state: RootState) => state.counter.value)
  const dispatch = useDispatch()



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
     <MainContainer flexdir="flex-col">
      <Layout className='p-5'>
        <Image
        alt='Logotype of Usuaal'
        src={Logotype}
        width={100}

        />
      </Layout>
      <Layout className='flex flex-row gap-5 '>
         <Button variant='outline' className='py-2' onClick={()=> dispatch(decrement())} label="Decrement"/>
        <h2 className='self-center'>{counter}</h2>
      <Button variant='normal' onClick={()=> dispatch(increment())} label="Increment" />
      </Layout>
      
      </MainContainer>   

     



      </main>
    </>
  )
}
